name: py35
dependencies:
- pip=9.0.1=py35_0
- python=3.5.4=0
- setuptools=36.6.0=py35_0
- wheel=0.30.0=py35_0
- pip:
  - appdirs==1.4.3
  - certifi==2017.7.27.1
  - chardet==3.0.4
  - colorama==0.3.9
  - fs==2.0.12
  - idna==2.6
  - jinja2==2.9.6
  - markupsafe==1.0
  - mondrian==0.4.0
  - packaging==16.8
  - pbr==3.1.1
  - psutil==5.4.0
  - pyparsing==2.2.0
  - pytz==2017.3
  - requests==2.18.4
  - six==1.11.0
  - stevedore==1.27.1
  - urllib3==1.22
  - whistle==1.0.0
  # for examples
  - pycountry ==17.9.23
