name: py35
dependencies:
- pip=9.0.1=py35_0
- python=3.5.2=0
- setuptools=20.3=py35_0
- wheel=0.29.0=py35_0
- pip:
  - colorama ==0.3.9
  - fs ==2.0.3
  - psutil ==5.2.2
  - requests ==2.13.0
  - stevedore ==1.21.0
  # for examples
  - pycountry ==17.9.23
